name: CDK setup

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - run: npm install -g corepack
    - run: corepack enable

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install dependencies
      run: yarn install --immutable
      working-directory: ./cdk-infra
      shell: bash
