name: CDK setup

runs:
  using: "composite"

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'


    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./cdk-infra
      shell: bash
