FROM mcr.microsoft.com/devcontainers/python:3.12

RUN pipx install uv

# install github action act
RUN curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
