name: Python CI

on: [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/setup-python

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linter
        run: uv run ruff check .

      - name: Run formatter
        run: uv run ruff format .

      - name: Run type check
        run: uv run pyright

      - name: Run tests
        run: uv run pytest -v
