name: Python CI

on: [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv, python
        uses: astral-sh/setup-uv@v7.1
        with:
          version: "0.9.2"
          python-version: 3.12
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linter
        run: uv run ruff check .

      - name: Run formatter
        run: uv run ruff format .

      - name: Run type check
        run: uv run pyright

      - name: Run tests
        run: uv run pytest -v

      - name: Minimize uv cache
        run: uv cache prune --ci
